### ISSUE TITLE
Any plans to make this friendlier for Israel usage?

### ISSUE THREAD

**Issue by justlevine** [zmanim/zman#13]
My understanding of the code is that you can't set `$galus` false on the `$zman` object or pass it via the getters (which means digging through the source code to find the correct function), and then not all of the functions have a galut switch (like `holidays()` which doesnt do the same checks as `is{$holidayname}( $galus )`. 

Are there any plans to fix this?

**Comment by tam5** [comment]
Hi @justlevine, that sounds like something we can add.

My thoughts are to have
1. the functions here: https://github.com/zmanim/zman/blob/master/src/Getters/Holidays.php accept an optional `galus` flag.
2. a global setter to set the mode for galus/israel which would in turn alter the default 

Would that satisfy your needs? Or are there other places that you see this missing.

@zachweix any input here?

**Comment by justlevine** [comment]
@tam5 what you're describing sounds perfect - especially the global setter!

**Comment by zachweix** [comment]
I was thinking the exact same thing. If implemented properly it shouldn't break any code, so we can even upgrade it without requiring any changes for the users

**Comment by tam5** [comment]
@justlevine @zachweix version [v1.3.0](https://github.com/zmanim/zman/releases/tag/v1.3.0) has been released which adds a global setter as described.

Thanks @zachweix.

Let us know if that works for you @justlevine, and then the only thing left is we should include it somewhere in the documentation (https://github.com/zmanim/zmanim.github.io)
