### ISSUE TITLE
[Feature Request] Omer

### ISSUE THREAD

**Issue by yskraus** [zmanim/zman#17]
can you add Sefira Count?

**Comment by tam5** [comment]
@yskraus Do you have an example of how that should look? Maybe an example usage?

**Comment by yskraus** [comment]
Explain please

**Comment by yskraus** [comment]
what im thinking 
$zman->sfiraDayHebrew
$zman->sfiraDay

if day is between 1st day of pesach and 1st day of shvies should return the count "יום  עשר יום שהם  שבועות ושלשה ימים לעומר" for 2021-04-12
else return false

**Comment by tam5** [comment]
> Explain please

There are a bunch of different ways I can see this being implemented, so I want to gauge how you would actually use it, to know what would be useful.

Some examples:

```php
$zman->sfiraDay                  // 5
$zman->sfiraDay                  // 5th day of the Omer
$zman->sfiraDayHebrew            // ה
$zman->sfiraDayHebrew            // ה בעומר
$zman->sfiraDayHebrew            // ה לעומר
$zman->sfiraCountAshkenaz        // היום חמשה ימים שהם...
$zman->sfiraCountSfard           // היום חמשה ימים שהם...
```

IMO the best thing would probably be the first option, to just return an unambiguous numerical value and let the caller do whatever they want with it.

**Comment by zachweix** [comment]
I agree that the first method is the best
